### ISSUE TITLE
Missing Utils.h file

### ISSUE THREAD

**Issue by MalwareCantFly** [0xcpu/Pin-ApiTracer#1]
Hi!
Great update!
But it looks like the "Utils.h" file is missing from the repo :)

**Comment by 0xcpu** [comment]
Hi!

Oh :smile: That's a good one. Thanks for telling me about this, I'll add it immediately. :+1:

**Comment by 0xcpu** [comment]
Thank you @MalwareCantFly !

**Comment by MalwareCantFly** [comment]
@0xcpu, much appreciated! 😃
